# cf. ./build-run.sh

FROM docker.io/library/debian:11
MAINTAINER mdavidsaver

ARG SCRIPT_VER=unspecified
LABEL aa-container.git=$SCRIPT_VER

ARG APPL_VER=unspecified
LABEL epicsarchiverap.git=$APPL_VER

RUN /build/prepare-in-run.sh

# mgmt
EXPOSE 17665
# retrieval
EXPOSE 17668

STOPSIGNAL SIGRTMIN+3
CMD [ "/sbin/init" ]
