name: "AA"

on: [push, pull_request]

defaults:
  run:
    shell: bash

jobs:
  podman:
    runs-on: "ubuntu-latest"
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: OS Deps
      run: |
        sudo apt-get update
        sudo apt-get install -y podman

    - name: Build AA
      run: podman build --squash -t epicsarchiverap:latest .

    - name: Test init
      run: |
        podman unshare install -d -o 1000 -g 1000 persist
        podman unshare cp template_changes.html persist/
        podman run --rm \
         -v ./persist:/persist \
         --hostname ${HOSTNAME} \
         epicsarchiverap:latest init
        find persist -not -type d

    - name: Add release tag
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        TAG=${{ github.ref }}
        podman image tag epicsarchiverap:latest epicsarchiverap:${TAG#refs/tags/}

    - name: Image info
      run: |
        podman image tree epicsarchiverap:latest
        podman image history epicsarchiverap:latest
        podman image inspect epicsarchiverap:latest

    - name: Save image
      run: |
        podman save -o epicsarchiverap.tar epicsarchiverap:latest
        xz -9e epicsarchiverap.tar

    - name: List image file
      run: |
        set -x
        ls -l epicsarchiverap.tar*
        xz -l *.xz
        tar -taf epicsarchiverap.tar*

    - name: Upload for testing
      uses: actions/upload-artifact@v4
      with:
        name: epicsarchiverap
        path: epicsarchiverap.tar*
        retention-days: 1
